# Generated by Django 2.2.1 on 2019-06-01 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='编号')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='年份')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='名称')),
                ('rating', models.FloatField(blank=True, null=True, verbose_name='评分')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('original_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='原名')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='姓名')),
                ('gender', models.CharField(blank=True, max_length=10, null=True, verbose_name='性别')),
                ('name_en', models.CharField(blank=True, max_length=256, null=True, verbose_name='英文姓名')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('born_place', models.CharField(blank=True, max_length=256, null=True, verbose_name='出生地')),
            ],
        ),
        migrations.CreateModel(
            name='MovieVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_link', models.CharField(default='https://baidu.com', max_length=256, verbose_name='链接')),
                ('source', models.CharField(default='自己搜', max_length=10, verbose_name='来源')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Subject.Movie', verbose_name='电影')),
            ],
        ),
        migrations.CreateModel(
            name='MovieTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=256, verbose_name='标签')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Subject.Movie', verbose_name='电影')),
            ],
        ),
        migrations.CreateModel(
            name='MoviePerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=10, null=True, verbose_name='职务')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Subject.Movie', verbose_name='电影')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Subject.Person', verbose_name='人')),
            ],
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=256, verbose_name='类型')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Subject.Movie', verbose_name='电影')),
            ],
        ),
    ]
